from wiki.utils import to_simplified

categories = [
    "戰國大名",
    "戰國武將",
    "戰國時代_(日本)",
    "戰國時代戰役_(日本)",
    "戰國時代事件_(日本)",
    "安土桃山時代",
    "安土桃山時代戰役",
    "安土桃山時代事件",
    "日本律令制官制",
    "武家政權",
    "室町幕府",
    "室町幕府官制",
    "關東公方",
    "大坂之役",
]

tc_ignore_sections = [
    "注釋",
    "參見",
    "註釋",
    "註解",
    "徵引",
    "腳註",
    "來源",
    "引用",
    "書目",
    "註腳",
    "參看",
    "系譜",
    "家族",
    "父母",
    "兄弟",
    "姊妹",
    "妻妾",
    "子女",
    "史料",
    "小說",
    "游戏",
    "遗品",
    "墓所",
    "遗物",
    "游戏",
    "出處",
    "附註",
    "附記",
    "影視劇",
    "肖像画",
    "铜像等",
    "參考來源",
    "模型玩具",
    "登場作品",
    "關連作品",
    "關連项目",
    "关联项目",
    "來源文獻",
    "參考資料",
    "外部連結",
    "參考文獻",
    "關聯項目",
    "影視改編",
    "基礎資訊",
    "進階資料",
    "參考連結",
    "相關條目",
    "肖像铜像等",
    "墓所与遗物",
    "墓所与灵庙",
    "太刀“山鸟毛”",
    "以描寫關原之戰為主的作品",
    "赤底牡丹唐草纹天鹅绒洋套",
    "国宝 上杉本洛中洛外图屏风",
    "註釋與出處連結",
    "歷代征夷大将军",
    "解釋和腳註",
    "參考書目",
    "幸若舞《敦盛》",
]
ignore_sections = [to_simplified(item) for item in tc_ignore_sections]
ignore_sections.extend(tc_ignore_sections)

tc_fuzzy_sections = ["參考", "連結", "文獻", "來源", "外部"]
fuzzy_sections = [to_simplified(item) for item in tc_fuzzy_sections]
fuzzy_sections.extend(tc_fuzzy_sections)

replace_links = ("file:", "image:", "category:", "檔案:", "文件:", "分類:", "分类:")
